/*
Copyright (c) 2019-2020 dayllenger

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

From https://github.com/gecko0307/dagon
*/

module shaderplayground.shaderloader;

import std.stdio;
import std.string: stripRight;
import bindbc.opengl;
import std.algorithm.comparison : min;
import shaderplayground.logger;

enum ShaderStage: ubyte
{
    vertex = 0,
    tessControl = 1,
    tessEval = 2,
    geometry = 3,
    fragment = 4,
    compute = 5
}

GLenum shaderStageToGLenum(ShaderStage stage)
{
    final switch (stage) with(ShaderStage)
    {
        case vertex:      return GL_VERTEX_SHADER;
    static if (glSupport >= GLSupport.gl40)
    {
        case tessControl: return GL_TESS_CONTROL_SHADER;
        case tessEval:    return GL_TESS_EVALUATION_SHADER;
    }
    else
    {
        case tessControl, tessEval: return 0;
    }
        case geometry:    return GL_GEOMETRY_SHADER;
        case fragment:    return GL_FRAGMENT_SHADER;
    static if (glSupport >= GLSupport.gl43)
        case compute:     return GL_COMPUTE_SHADER;
    else
        case compute:     return 0;
    }
}

import shaderplayground.shadercommon;

/// Compile single shader from source
GLuint compileShader(string source, const ShaderStage stage)
{
    errors("shad 0");
    // create a shader
    GLuint shaderId = glCreateShader(shaderStageToGLenum(stage));

    errors("shad 1");
    // compile the shader
    const char* csource = source.ptr;
    GLint length = cast(GLint) source.length;
    glShaderSource(shaderId, 1, &csource, &length);
    errors("shad 2");
    glCompileShader(shaderId);
    errors("shad 3");

    // check the shader
    if (!checkCompilation(shaderId))
    {
        shaderId = 0;
        glDeleteShader(shaderId);
    }
    errors("shad 4");

    return shaderId;
}

/// Link compiled shaders
GLuint linkShaders(const GLuint[] shaderIds...)
{
    // create and link program
    GLuint programId = glCreateProgram();
    errors("prog 1");
    foreach (sh; shaderIds)
        glAttachShader(programId, sh);
    glLinkProgram(programId);
    errors("prog 2");

    // check the program
    if (!checkLinking(programId))
    {
        programId = 0;
        glDeleteProgram(programId);
    errors("prog 3");
    }

    // delete the program parts
    foreach (sh; shaderIds)
    {
        glDetachShader(programId, sh);
        glDeleteShader(sh);
    errors("prog 4 ");
    }

    errors("prog 5");
    return programId;
}

private enum logMaxLen = 1023;
alias LogBuffer = char[logMaxLen + 1];

bool checkShaderCompiled(const uint shaderId)
{
    GLint status = GL_FALSE;
    glGetShaderiv(shaderId, GL_COMPILE_STATUS, &status);
    const bool ok = status != GL_FALSE;
    return ok;
}

bool checkShaderProgramLinked(const uint programId)
{
    GLint status = GL_FALSE;
    glGetProgramiv(programId, GL_LINK_STATUS, &status);
    const bool ok = status != GL_FALSE;
    return ok;
}


char[] getLog(alias getivFunc)(return ref scope LogBuffer buffer, const uint objectId)
{
    GLint infolen;
    getivFunc(objectId, GL_INFO_LOG_LENGTH, &infolen); // includes \0
    if (infolen > 1)
    {
        glGetShaderInfoLog(objectId, logMaxLen, null, buffer.ptr);
        infolen = min(infolen - 1, logMaxLen);
        char[] s = stripRight(buffer[0..infolen]);
        return s;
    }
    return buffer[0..0];
}

auto getCompilationLog(return ref scope LogBuffer buffer, const uint shaderId)
{
    return getLog!glGetShaderiv(buffer, shaderId);
}

auto getLinkingLog(return ref scope LogBuffer buffer, const uint programId)
{
    return getLog!glGetProgramiv(buffer, programId);
}

private bool checkCompilation(const GLuint shaderId)
{
    const ok = checkShaderCompiled(shaderId);
    LogBuffer buffer = 0;
    auto s = getCompilationLog(buffer, shaderId);
    if (!ok)
        g_Logger.error("Failed to compile shader.");
    if (s.length > 0)
        g_Logger.log(s);
    return ok;
}

private bool checkLinking(const GLuint programId)
{
    const ok = checkShaderProgramLinked(programId);
    LogBuffer buffer = 0;
    auto s = getLinkingLog(buffer, programId);
    if (!ok)
        g_Logger.error("Failed to link shaders.");
    if (s.length > 0)
        g_Logger.log(s);
    return ok;
}
